### ISSUE TITLE
Initialize repository with base configuration

### ISSUE THREAD

**Issue by nishantpal1911** [nishantpal1911/applicant-tracking-system-web#3]
### Description
- The start of something great! We are creating an Application Tracking System for corporate HRs and employees.
- The main goals of this system is to provide a single interface / UI for -
  1. HR to track and edit progress of all applicants from all sources for programming assessment and interview levels.
  2. Employees to find all details related to the assigned candidates for paper checking and interview process.

### Why are we building this?
- All the pain points and frustrations that are faced by the HR and employees during the hiring process as well as the goals that this system aims to achieve are listed here - https://www.figma.com/board/yBItHfb60I0gUBAuNHCtS4/Product-Planning?node-id=567-573&t=flI5CUtAfI9jP7UU-4

### Designs
- https://www.figma.com/design/9CoHc6iF6fi9bzXRjWdORz/Design?node-id=0-1&t=uiPLe27hgzvLLNWX-1

### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [x] Initialise the GitHub repository on CLI
- [x] Setup React with TypeScript:
  - React - https://create-react-app.dev/
  - Typescript - https://www.typescriptlang.org/
- [x] Setup linting with ESLint and code formatting with Prettier
- [x] Setup Tailwind CSS for using pre-defined styles in `.tsx` files directly and Class Variance Authority (cva) for organizing the style definitions.
  - Tailwind CSS - https://tailwindcss.com/
  - Class Variance Authority - https://cva.style/docs
- [x] Setup Material UI Icons - https://mui.com/material-ui/material-icons

**Comment by nishantpal1911** [comment]
Completed in Bootstrap commit: https://github.com/nishantpal1911/applicant-tracking-system-web/commit/4d13df4b507ba4b7c56033622d5b9f6c7f8400af
